export const products = [
  {
    id: 1,
    name: '安享赢2024年第001期',
    minimumInvestment: 10,
    depositTerm: '1年',
    rate: '1.5%',
    description: '这是一款优质产品，请放心购买',
  },
  {
    id: 2,
    name: '安享赢2024年第002期',
    minimumInvestment: 100,
    depositTerm: '2年',
    rate: '2.5%',
    description: '这是一款优质产品，请放心购买',
  },
  {
    id: 3,
    name: '安享赢2024年第003期',
    minimumInvestment: 1000,
    depositTerm: '3年',
    rate: '3.5%',
    description: '这是一款优质产品，请放心购买',
  },
  {
    id: 4,
    name: '安享赢2024年第004期',
    minimumInvestment: 10000,
    depositTerm: '1个月',
    rate: '4.5%',
    description: '这是一款优质产品，请放心购买',
  },
  {
    id: 0,
    name: '安享赢2024年第005期',
    minimumInvestment: 10000,
    depositTerm: '1个月',
    rate: '4.5%',
    description: '这是一款优质产品，请放心购买',
  },
  {
    id: 5,
    name: '安享赢2024年第006期',
    minimumInvestment: 1,
    depositTerm: '1天',
    rate: '5.5%',
    description: '这是一款优质产品，请放心购买',
  },
  {
    id: 6,
    name: '安享赢2024年第007期',
    minimumInvestment: 10,
    depositTerm: '1年',
    rate: '1.5%',
    description: '这是一款优质产品，请放心购买',
  },
  {
    id: 7,
    name: '安享赢2024年第008期',
    minimumInvestment: 100,
    depositTerm: '2年',
    rate: '2.5%',
    description: '这是一款优质产品，请放心购买',
  },
  {
    id: 8,
    name: '安享赢2024年第009期',
    minimumInvestment: 1000,
    depositTerm: '3年',
    rate: '3.5%',
    description: '这是一款优质产品，请放心购买',
  },
  {
    id: 9,
    name: '安享赢2024年第0010期',
    minimumInvestment: 10000,
    depositTerm: '1个月',
    rate: '4.5%',
    description: '这是一款优质产品，请放心购买',
  },
];
